Був присутній на парі.


In [1]:
import numpy as np
np.__version__

'2.0.2'

In [3]:
matrix = np.random.randint(1, 6, size=(3, 3))
matrix

array([[4, 4, 4],
       [1, 3, 3],
       [1, 2, 3]])

In [4]:
np.linalg.det(matrix)

np.float64(7.999999999999998)

In [5]:
product = np.prod(matrix)
product

np.int64(3456)

In [6]:
prod_1 = np.prod(matrix[0])
prod_2 = np.prod(matrix[1])
prod_3 = np.prod(matrix[2])
prod_1*prod_2*prod_3

np.int64(3456)

In [7]:
np.sum(matrix)

np.int64(25)

In [8]:
np.max(matrix)

np.int64(4)

In [9]:
np.min(matrix)

np.int64(1)

In [10]:
np.mean(matrix)

np.float64(2.7777777777777777)

In [11]:
np.sqrt(matrix)

array([[2.        , 2.        , 2.        ],
       [1.        , 1.73205081, 1.73205081],
       [1.        , 1.41421356, 1.73205081]])

In [12]:
np.sum(matrix, axis=1).reshape(-1, 1)

array([[12],
       [ 7],
       [ 6]])

In [13]:
matrix.sum(axis=1).reshape(-1, 1)

array([[12],
       [ 7],
       [ 6]])

In [15]:
x = np.matrix([[1, 2], [4, 3]])
x

matrix([[1, 2],
        [4, 3]])

In [16]:
x.sum(axis=1)

matrix([[3],
        [7]])

In [17]:
x.sum(axis=1, dtype='float')

matrix([[3.],
        [7.]])

In [30]:
vector = np.random.randint(0, 10, size=25)
vector

array([3, 3, 2, 2, 7, 6, 3, 1, 4, 5, 1, 3, 9, 4, 8, 4, 9, 4, 4, 4, 9, 8,
       1, 5, 4])

In [23]:
np.sort(vector)[::-1]

array([9, 9, 6, 6, 5, 5, 4, 4, 4, 4, 3, 3, 3, 3, 3, 2, 1, 1, 1, 1, 1, 1,
       1, 0, 0])

In [35]:
from scipy import stats

stats.mode(vector)



ModeResult(mode=np.int64(4), count=np.int64(7))

In [36]:
np.median(vector)


np.float64(4.0)

In [37]:
np.mean(vector)


np.float64(4.52)

In [40]:
np.max(vector)

np.int64(9)

In [39]:

np.min(vector)

np.int64(1)

In [41]:
np.random.randint(1, 11, size=(4, 4))

array([[ 7,  3,  7,  2],
       [ 6,  2,  8,  2],
       [10,  7,  5,  6],
       [ 2,  4,  5,  1]])

In [46]:
x = np.arange(9.)
x

array([0., 1., 2., 3., 4., 5., 6., 7., 8.])

In [45]:
x.reshape((3, 3))

array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]])

In [47]:
np.arange(3.)

array([0., 1., 2.])