<a href="https://colab.research.google.com/github/AndriyTalalayev/Machine_learning/blob/main/%D0%9B%D0%A0_1_%D0%A2%D0%B0%D0%BB%D0%B0%D0%BB%D0%B0%D1%94%D0%B2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Був присутній на парі.


In [1]:
import numpy as np
np.__version__

'2.0.2'

In [3]:
matrix = np.random.randint(1, 6, size=(3, 3))
matrix

array([[4, 4, 4],
       [1, 3, 3],
       [1, 2, 3]])

In [4]:
np.linalg.det(matrix)

np.float64(7.999999999999998)

In [5]:
product = np.prod(matrix)
product

np.int64(3456)

In [6]:
prod_1 = np.prod(matrix[0])
prod_2 = np.prod(matrix[1])
prod_3 = np.prod(matrix[2])
prod_1*prod_2*prod_3

np.int64(3456)

In [7]:
np.sum(matrix)

np.int64(25)

In [8]:
np.max(matrix)

np.int64(4)

In [9]:
np.min(matrix)

np.int64(1)

In [10]:
np.mean(matrix)

np.float64(2.7777777777777777)

In [11]:
np.sqrt(matrix)

array([[2.        , 2.        , 2.        ],
       [1.        , 1.73205081, 1.73205081],
       [1.        , 1.41421356, 1.73205081]])

In [12]:
np.sum(matrix, axis=1).reshape(-1, 1)

array([[12],
       [ 7],
       [ 6]])

In [13]:
matrix.sum(axis=1).reshape(-1, 1)

array([[12],
       [ 7],
       [ 6]])

In [15]:
x = np.matrix([[1, 2], [4, 3]])
x

matrix([[1, 2],
        [4, 3]])

In [16]:
x.sum(axis=1)

matrix([[3],
        [7]])

In [17]:
x.sum(axis=1, dtype='float')

matrix([[3.],
        [7.]])

In [18]:
vector = np.random.randint(0, 10, size=25)
np.sort(vector)[::-1]

array([9, 9, 6, 6, 5, 5, 4, 4, 4, 4, 3, 3, 3, 3, 3, 2, 1, 1, 1, 1, 1, 1,
       1, 0, 0])